// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.ArchiveInstallRequest} request
 * @returns {$CancellablePromise<$models.ArchiveInstallResult>}
 */
export function ApplyArchive(request) {
    return $Call.ByID(2557078979, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.InstallRequest} request
 * @returns {$CancellablePromise<string>}
 */
export function ApplyFile(request) {
    return $Call.ByID(846880309, request);
}

/**
 * @returns {$CancellablePromise<$models.MASStatus>}
 */
export function GetMASStatus() {
    return $Call.ByID(767909844).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} operationID
 * @returns {$CancellablePromise<void>}
 */
export function Recover(operationID) {
    return $Call.ByID(1449242715, operationID);
}

/**
 * @returns {$CancellablePromise<$models.LocalSubmod[]>}
 */
export function ScanLocalSubmods() {
    return $Call.ByID(1364442018).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} root
 * @returns {$CancellablePromise<$models.MASStatus>}
 */
export function SetMASRoot(root) {
    return $Call.ByID(958382738, root).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} operationID
 * @param {string} uninstallOperationID
 * @returns {$CancellablePromise<string>}
 */
export function Uninstall(operationID, uninstallOperationID) {
    return $Call.ByID(3087482905, operationID, uninstallOperationID);
}

// Private type creation functions
const $$createType0 = $models.ArchiveInstallResult.createFrom;
const $$createType1 = $models.MASStatus.createFrom;
const $$createType2 = $models.LocalSubmod.createFrom;
const $$createType3 = $Create.Array($$createType2);
