// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ArchiveInstallRequest {
    /**
     * Creates a new ArchiveInstallRequest instance.
     * @param {Partial<ArchiveInstallRequest>} [$$source = {}] - The source object to create the ArchiveInstallRequest.
     */
    constructor($$source = {}) {
        if (!("operation_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["operation_id"] = "";
        }
        if (!("archive_base64" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["archive_base64"] = "";
        }
        if (!("expected_sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expected_sha256"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchiveInstallRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ArchiveInstallRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArchiveInstallRequest(/** @type {Partial<ArchiveInstallRequest>} */($$parsedSource));
    }
}

export class ArchiveInstallResult {
    /**
     * Creates a new ArchiveInstallResult instance.
     * @param {Partial<ArchiveInstallResult>} [$$source = {}] - The source object to create the ArchiveInstallResult.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["files"] = 0;
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchiveInstallResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ArchiveInstallResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField2_0($$parsedSource["warnings"]);
        }
        return new ArchiveInstallResult(/** @type {Partial<ArchiveInstallResult>} */($$parsedSource));
    }
}

export class InstallRequest {
    /**
     * Creates a new InstallRequest instance.
     * @param {Partial<InstallRequest>} [$$source = {}] - The source object to create the InstallRequest.
     */
    constructor($$source = {}) {
        if (!("operation_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["operation_id"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("expected_sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expected_sha256"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstallRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallRequest(/** @type {Partial<InstallRequest>} */($$parsedSource));
    }
}

export class LocalSubmod {
    /**
     * Creates a new LocalSubmod instance.
     * @param {Partial<LocalSubmod>} [$$source = {}] - The source object to create the LocalSubmod.
     */
    constructor($$source = {}) {
        if (!("directory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["directory"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {LocalSubmodFile[]}
             */
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalSubmod instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalSubmod}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField3_0($$parsedSource["files"]);
        }
        return new LocalSubmod(/** @type {Partial<LocalSubmod>} */($$parsedSource));
    }
}

export class LocalSubmodFile {
    /**
     * Creates a new LocalSubmodFile instance.
     * @param {Partial<LocalSubmodFile>} [$$source = {}] - The source object to create the LocalSubmodFile.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalSubmodFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalSubmodFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalSubmodFile(/** @type {Partial<LocalSubmodFile>} */($$parsedSource));
    }
}

export class MASStatus {
    /**
     * Creates a new MASStatus instance.
     * @param {Partial<MASStatus>} [$$source = {}] - The source object to create the MASStatus.
     */
    constructor($$source = {}) {
        if (!("root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["root"] = "";
        }
        if (!("game_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["game_path"] = "";
        }
        if (!("valid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["valid"] = false;
        }
        if (!("game_exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["game_exists"] = false;
        }
        if (!("submods" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["submods"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MASStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MASStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MASStatus(/** @type {Partial<MASStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = LocalSubmodFile.createFrom;
const $$createType2 = $Create.Array($$createType1);
